spring.application.name=question-service
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/questiondb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=PGAdmin@4

## NOTE: The below line is necessary...!!spring.jpa.properties.hibernate,dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA & Hibernate
spring.jpa.show-sql=true

# "validate" for production
spring.jpa.hibernate.ddl-auto=update

# Related to Eureka-Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/