spring.application.name=service-registry
server.port=8761

eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

#eureka.instance.lease-renewal-interval-in-seconds=15   # Send heartbeat every 5 sec
#eureka.instance.lease-expiration-duration-in-seconds=30  # Mark as down if no heartbeat for 15 sec
#eureka.server.eviction-interval-timer-in-ms=5000  # Run eviction every 5 sec
